spring.application.name=ProductCatalogService
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/product_catalog_service
#spring.datasource.url=jdbc:mysql://product-catalog-service.cj8qg2owc6je.eu-north-1.rds.amazonaws.com/product_catalog_service
spring.datasource.username=myuser
spring.datasource.password=secret
#spring.datasource.username=admin
#spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql=true